name: Github Actions 실행시키기

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
#    runs-on: self-hosted
    steps:
      - name: SSH로 EC2에 원격 접속 (applyboy 없이)
        run: |
          rm -rf ${{ secrets.EC2_KEY_PATH }}
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ${{ secrets.EC2_KEY_PATH }}
          chmod 400 ${{ secrets.EC2_KEY_PATH }}
          ssh-keygen -R ${{ secrets.EC2_HOST }}
          ssh -t -i ${{ secrets.EC2_KEY_PATH }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/github-actions-practice
            git pull origin main
          EOF
          rm -rf ${{ secrets.EC2_KEY_PATH }}
