# workflow 이름
name: Github Actions 실행시키기

# event: 실행 시점
on:
  push:
    branches:
      - main

# 하나의 workflow 1개 이상의 job 구성
# 여러 job 기본적으로 병렬로 수행
jobs:
  My-Deploy-Job: # job 식별 위한 id
    runs-on: ubuntu-latest # ubuntu 환경 + 가장 최신 버전

    # step: 특정 작업을 수행하는 가장 작은 단위
    # job 여러 step 으로 구성
    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "good "
          echo "evening"

      - name: Github Actions 에 저장되어있는 변수사용해보기
        run: |
          echo $GITHUB_SHA # 해당 commit 고유값
          echo $GITHUB_REPOSITORY

      - name: 노출시키고 싶지 않은 값
        run:
          echo ${{ secrets.SECRET_HOBBY }}